# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wemubis_ <wemubis_@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/23 00:52:46 by wemubis_          #+#    #+#              #
#    Updated: 2022/07/23 02:46:30 by wemubis_         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FLAG = -Wall -Werror -Wextra

NAME = rush_02

PROGM = ... \
		... \
		... \
		... \
		... \
		... \
		...

all : $(NAME)

$(NAME) :
	@gcc $(FLAG) $(NAME) $(PROGM)

clean :
	@/bin/rm -rf ...

fclean : clean
	@/bin/rm -rf $(NAME)

re : fclean all
